name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::475411231343:role/github-actions-role
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 475411231343.dkr.ecr.us-east-1.amazonaws.com

      - name: Build image
        run: docker build -t my-app ./my-app

      - name: Tag image
        run: docker tag my-app:latest 475411231343.dkr.ecr.us-east-1.amazonaws.com/my-app:${{ github.sha }}

      - name: Push image
        run: docker push 475411231343.dkr.ecr.us-east-1.amazonaws.com/my-app:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # 🔐 login ECR
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 475411231343.dkr.ecr.us-east-1.amazonaws.com

            # 🛑 وقف القديم
            docker stop my-app || true
            docker rm my-app || true

            # 📦 اسحب النسخة الجديدة (IMPORTANT 🔥)
            docker pull 475411231343.dkr.ecr.us-east-1.amazonaws.com/my-app:${{ github.sha }}

            # 🚀 شغل النسخة الجديدة
            docker run -d -p 80:3000 --name my-app 475411231343.dkr.ecr.us-east-1.amazonaws.com/my-app:${{ github.sha }}